### ISSUE TITLE
We should change the way Patients, Providers and Problems are represented.

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#145]
1) When in our current app would a Patient use any of the information it holds about the providers?  Should it hold provider data at all?  Is there a use case or an activity that involves this?

2) Patient should not directly store a list of problems as they store unnecessary data. The problem database stores the problem objects so a patient shouldn't also store their problem objects. They should instead store the ids of the problem objects so the Provider can easily retrieve them from the database only when it needs to.

3) In the same way as above, the Problem object should store ids of the associated Records and Patient Records.  Also the Provider should not store the Patients, but the Patient ids.

4) How should a Provider attach a new Record to a Patient's problem?  He would have to edit (write to) the Problem's list of record ids.  This is bad because it is owned by the Patient, not the Provider.  Maybe that's not a bad thing?  We could let the Provider write but only to that one property?  Other idea is that the controller responsible for showing records and patient records will be responsible for looking in the records database for any records associated with the problem that a provider has created.  The provider can then just attach the id of the problem to his record and it will be picked up by the query.

We need to discuss this as early as we can in the project so we don't have to change a ton of stuff later on.

**Comment by tnguyen10** [comment]
1. I don't think we need to store provider datas since I don't think there's any requirement regarding that

2,3. If this is implemented then we should auto-generate problem id and record id. Also, how should these be store in files? 
We could have only 1 file each for patient, problem, record. Each patient is identifiable by provider id and its own patient id. Each problem is identifiable by provider id (if provider search), patient id, problem id. Each record is identifiable by provider id (if provider search), patient id, problem id, record id. We also have to be careful in insertion and deletion to keep track of the ids. 

4) To build upon on what you said about the provider attach the problem id to his record. Is it possible for all these list to not be initialize, but when we need them we just read from the database (using appropriate id), that way we won't have store objects list within objects. -> However this could be a problem with offline and online switch when we're reading from different databases, (but this problem will appear regardless?)

**Comment by tnguyen10** [comment]
Does this means that in the offline database, patient won't have list of problem ids? Also I'm not quite sure if saving DatabasePatient (without contact info and others) onto online database is a good idea? .... I'm not sure what is the best way to implement this. But I think we should store the same thing/ format of object on both offline and elastic search database.

 (How we synchronize them can be resolved in issue [102](https://github.com/CMPUT301F18T20/MedicalPhotoRecord/issues/102) since I was wrong to assume that the offline database is the most reliable one,as the online database can be updated from another source and the offline database won't be able to have those new changes)

My suggestion is we don't have to store the problem ids or problems list onto database, but it will be fetched from the database when we need it using controller.

And inside the database, the format for 
patient file would be : (id, email, phone, ...)
problem file would be: (patientId, problemId, title, description, ...)
record file would be: (patientId, problemId, recordId, title, description, ...)

We could load these files directly into list of patients, problems, records and manually search for those with same patientId, problemId or we could write in either offline save load or elastic search a way to do that. Either way, the patient would not have direct access to its list of problem, but has to get it via database. 

A pros: for this would be, the list should be consistent (accounting for offline and online synchronization)
A cons: I don't think it's efficient to fetch list from database every time we need it, but depends on how many time we need the list, it may not be that bad? (insertion and deletion is fine: since database include, ignore problems with same patientId)

Not sure if this implementation is the best one, but just a suggestion.

**Comment by modelarious** [comment]
Do we need an offline query?

**Comment by modelarious** [comment]
In that example, database patient would have all the attributes of a patient, but any of the arraylists of objects it has are replaced by null and it gains a list of ids to use when fetching the associated objects from the database. So they still have all the contact info and all that.

I like the method you're proposing here and I agree with it. It feels like it's not very OO, but it also feels like the most logical way to go about it.

Also, I don't think we should worry too much about loading often from the databases. We want every activity and action to have the most up to date information available... Though we need to be careful of the order of fetching and accessing if we are accessing by index.

**Comment by modelarious** [comment]
How does this affect the UML though? I feel like this change would decimate the OO design and make it more relational (like SQL)... Should we check with the TA to see if he has any suggestions?

**Comment by tnguyen10** [comment]
Yes, we should check with the TA. I'll email him right now. We need to figure this out early since we need it for almost every activities in the app

**Comment by modelarious** [comment]
Thanks for getting that done.  Can you post the results here once he replies?

**Comment by modelarious** [comment]
We'll need to add the proposed ids as well as a "date last modified" for reasons discussed in #102

**Comment by kerryli33** [comment]
Hey guys, just wondering if we are implementing the idea of storing id's of problem and patients in the database and using that as a reference in the object. If so, what are the initial steps of implementing this? Would we have to delete the list of problems from patient and replace it with its ID instead and same for Provider + patient list and just use the ID's in the search query to fetch the object? We should probably figure this out before doing any other work

**Comment by modelarious** [comment]
I'm thinking we should do it like this:

```
public class Problem {
    protected String problemID; //unique for problems, id from elasticsearch
    ...
}
```
```
public class Record (and patient record) {
    String recordID; //unique for records, id from elasticsearch
    String associatedToProblemID; //this is the problemID from above
    ...
}
```


When we need the records associated with a problem, we query the "associatedToProblemID" field in the record object for our problemID.  We keep the "records" array of Record objects in the Problem object and set it to null when storing it to conserve room.  When we need to use the "records" array, we populate it like:

```
Problem.setRecords(ElasticsearchRecordsController.getRecordsTask().execute( UserID ).get());
```

and then all of our tested model functionality like problem.getRecord() will be executed on the up to date dataset.

This applies to all arrays of objects in the assignment, so the list of assigned patients for a provider, list of problems for a patient, list of records for a problem, list of patient records for a problem and likely the list of photos and body location photos in the patient record.

**Comment by modelarious** [comment]
#172 Seems to be tracking this issue now, and I'm tackling it, so we can close this issue
